### ISSUE TITLE
question about the  mix models

### ISSUE THREAD

**Issue by CatchBeliF** [AdamKortylewski/CompositionalNets#2]
Hello, thanks for your work. 
When we download your models,we found that each category has a corresponding model,
such as"mmodel_aeroplane_K4_FEATDIM512_pool4_specific_view.pickle"  but we didn't find the method to generate the model in the code
We want to know how to generate such model so that we can add new categories.

**Comment by AdamKortylewski** [comment]
Hi,
we initialize the mixture models by clustering the training images based on their vMF kernel encodings. After the initial clustering you can compute the mixture models (alpha parameters in the paper) with maximum likelihood. I will try to find time to upload our initialization code next week and will notify you when this has happened.

**Comment by CatchBeliF** [comment]
Thank you very much!

**Comment by AdamKortylewski** [comment]
This will take a little longer as expected because we are currently very busy. But we try our best to make this happen until the end of this month. Sorry for that.

**Comment by CatchBeliF** [comment]
Sorry for late reply,thank you again for your busy reply.We are looking forwards to your codes.

**Comment by MorganeAyle** [comment]
Hello, thank you for your interesting work. Are there any updates as to when you will be able to upload the initialization code?

**Comment by AdamKortylewski** [comment]
Hi, thanks for your interest. Yes, it should be online some time tomorrow.

**Comment by AdamKortylewski** [comment]
I have added code for initializing CompNets but have not extensively tested everything, therefore please let me know if you experience any issues.

**Comment by AdamKortylewski** [comment]
I am closing this issue, as the initialization code is now available.
