### ISSUE TITLE
Empty clutter_feats in demo.py

### ISSUE THREAD

**Issue by mattesko** [AdamKortylewski/CompositionalNets#3]
I'm trying to experiment with the code by running `python Code/demo.py` but get the following error:
```
Traceback (most recent call last):
  File "Code/demo.py", line 34, in <module>
    net = Net(extractor, weights, vMF_kappa, occ_likely, mix_models, bool_mixture_bg=bool_mixture_model_bg,compnet_type=compnet_type, num_mixtures=num_mixtures, vc_thresholds=cfg.MODEL.VC_THRESHOLD)
  File "/content/CompositionalNets/Code/model.py", line 48, in __init__
    compnet_type, vMF_kappa)
  File "/content/CompositionalNets/Code/model.py", line 129, in get_clutter_model
    vMF_kappa, max_it=150, tol=1e-10)
  File "/content/CompositionalNets/Code/vMFMM.py", line 45, in fit
    centers_i.append(np.random.choice(rdn_index))
  File "mtrand.pyx", line 1125, in mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```
This happens when trying to fit the 'vmf' clutter model at line 129 in `get_clutter_model` by passing an empty list of `clutter_feats`. Any chance I could get help with this?

My environment:
OS: Ubuntu 18.04.3 LTS
Release: 18.04
Python: 3.6.9
Cuda: Release 10.1, V10.1.243
PyTorch: 1.2.0

**Comment by AdamKortylewski** [comment]
This seems to be an issue with the images used to train the clutter model. Have you checked if the list of files is empty? (l.94 in model.py)

**Comment by mattesko** [comment]
I see thanks! I had to change the name of the `background_images` folder to `background_images_for_learning` since that's the folder specified in line 77 in model.py. It resolved my issue.
