### ISSUE TITLE
About the code in model.py

### ISSUE THREAD

**Issue by StetchPlane** [AdamKortylewski/CompositionalNets#6]
Thanks for your excellent work.
https://github.com/AdamKortylewski/CompositionalNets/blob/9affa4d89fbb2debbe723d9c8e5956000aa6f719/Code/model.py#L146
Why is there no normalization in the calculation of 'general'?
https://github.com/AdamKortylewski/CompositionalNets/blob/9affa4d89fbb2debbe723d9c8e5956000aa6f719/Code/model.py#L122
But the former 'noise' and 'white' are normalized.

**Comment by AdamKortylewski** [comment]
This is a bug, all vectors should be normalized.

Best
Adam
